Handling failuresCloudera Docs
Handling failures


You can use a failure Output Port to notify the Cloud function that an
        invocation has failed. At that point, the Cloud function may automatically retry the
        invocation, if configured in the Trigger section, for up to seven
        days. After that, if it still fails, the Cloud function will simply drop the event
        notification. This could result in data loss, as it means that your Cloud function will not
        have a chance to process the data again.


